```yaml
name: Build, Push, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [urp, alex, raven]
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ matrix.service }}:${IMAGE_TAG} ./services/${{ matrix.service }}
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ matrix.service }}:${IMAGE_TAG}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name pharma-lab-eks

      - name: Deploy with Helm
        run: |
          helm upgrade --install urp ./services/urp/helm/urp-chart --set image.tag=${GITHUB_SHA}
          helm upgrade --install alex ./services/alex/helm/alex-chart --set image.tag=${GITHUB_SHA}
          helm upgrade --install raven ./services/raven/helm/raven-chart --set image.tag=${GITHUB_SHA}
