replicaCount: 2

image:
  repository: <ECR_URL>/SERVICE
  tag: "latest"

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: SERVICE-secrets
        key: db-url
